### ISSUE TITLE
Change to ng-indeterminate and make it as a PR to angularjs core

### ISSUE THREAD

**Issue by leocaseiro** [angular-ui/ui-indeterminate#2]
Hi, I really liked this directive. It works perfect.

I was wondering, if this `ui-utils` is deprecated and the directive `ui-indeterminate` is working just fine (test up to angularjs#1.5.1), why don't make it as `ng-indeterminate` inside core?

**Comment by ProLoser** [comment]
You have to convince the core team, not us.

**Comment by PowerKiKi** [comment]
`ui-utils` is deprecated but `ui-indeterminate` continues to live in this repository. Feel free to create PR to improve it and/or try to convince the core team for inclusion in the core.
